version: 2

jobs:
  lint:
    docker:
      - image: circleci/node:lts
    working_directory: ~/pingcap/blog-cn
    steps:
      - checkout

      - run:
          name: "Check links"
          command: |
            hack/verify-links.sh

workflows:
  version: 2
  lint:
    jobs:
      - lint
